module.exports = {
  name: 'europe',
  description: 'Europe',
  options: {
    frequency: 60 * 5.5,
  },
  urls: [
    "https://www.unilever-fima.com/",
    "https://www.unilever.at/",
    "https://www.unilever.be/",
    "https://www.unilever.be/fr/",
    "https://www.unilever.ch/",
    "https://www.unilever.co.uk/",
    "https://www.unilever.cz/",
    "https://www.unilever.de/",
    "https://www.unilever.dk/",
    "https://www.unilever.es/",
    "https://www.unilever.fi/",
    "https://www.unilever.fr/",
    "https://www.unilever.gr/",
    "https://www.unilever.hu/",
    "https://www.unilever.ie/",
    "https://www.unilever.it/",
    "https://www.unilever.nl/",
    "https://www.unilever.pl/",
    "https://www.unilever.ro/",
    "https://www.unilever.se/",
    "https://www.unilever.sk/",
    "https://www.unilever.ua/",
  ],
};
